name: io_ui
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1

  # UI
  flutter_svg: ^2.0.7
  flutter_gen: ^5.3.2
  dropdown_button2: ^2.3.7

  # Utils
  intl: ^0.18.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner:
  flutter_gen_runner:

flutter:

  assets:
    - assets/fonts/

  fonts:
    - family: Paragraph
      fonts:
        - asset: assets/fonts/Paragraph-Light.ttf
          weight: 300
        - asset: assets/fonts/Paragraph-Medium.ttf
          weight: 500
        - asset: assets/fonts/Paragraph-Bold.ttf
          weight: 700
